config/routes.rb
Rails.application.routes.draw do


  resources :tests
  resources :messages
  resources :reservations
  post '/rate' => 'rater#create', :as => 'rate'
  get 'static_pages/home'

  get 'static_pages/contact'

  get 'static_pages/about_us'

  root 'static_pages#home'

  resources :routes do 
    resources :messages
  end
	resources :users do
	  resources :user_comments
	end
  resources :routes do
    resources :user_comments
  end


  devise_for :users , :path_prefix => 'devise' , 
  controllers: {  confirmations: 'confirmations'  ,registrations: 'registrations' }

  get 'trajets' => 'routes#index'
  get 'contact' => 'static_pages#contact'
  get 'all_routes' => 'routes#all_routes'
  post 'all_routes' => 'routes#all_routes'
  get 'manage' => 'users#manage_users'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  	@last_routes = Route.last(3)
  end

  def contact
  end

  def about_us
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about_us.html.erb
<h1>StaticPages#about_us</h1>
<p>Find me in app/views/static_pages/about_us.html.erb</p>

app/views/static_pages/contact.html.erb
   
  

  <div class="site-section">
    <div class="container">
      <div class="row block-9">
        <div class="col-md-6 pr-md-5">
          <form action="#">
            <div class="form-group">
              <input type="text" class="form-control px-3 py-3" placeholder="Your Name">
            </div>
            <div class="form-group">
              <input type="text" class="form-control px-3 py-3" placeholder="Your Email">
            </div>
            <div class="form-group">
              <input type="text" class="form-control px-3 py-3" placeholder="Subject">
            </div>
            <div class="form-group">
              <textarea name="" id="" cols="30" rows="7" class="form-control px-3 py-3" placeholder="Message"></textarea>
            </div>
            <div class="form-group">
              <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
            </div>
          </form>
        
        </div>

        <div class="col-md-6" id="map"></div>
      </div>
    </div>
  </div>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Yuso-Covoit</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">

  </head>
  <body>
    

  
  <div class="block-31" style="position: relative;">
    <div class="owl-carousel loop-block-31 ">
      <div class="block-30 item" style="background-image: url('assets/bg_1.jpg');">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-md-10">
              <h2 class="subheading-sm">Le covoiturage gratuit, collaboratif et libre, pour tous vos trajets</h2>
              <% if user_signed_in? %>
                <p><%= link_to new_route_path do %><span class="btn btn-primary">Déposer un trajet</span><% end %></p>
              <% else %>
                <p><%= link_to new_user_session_path do %><span class="btn btn-primary">Déposer un trajet</span><% end %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="container">
      <div class="row mb-5">
        <div class="col-md-12">

          <div class="block-32">
            <%= form_tag(all_routes_path method: :get) do %>

               <div class="row">
                <div class="col-md-6 mb-3 mb-lg-0 col-lg-3">
                  <label for="depart">Point de départ:</label>
                  <div class="field-icon-wrap">
                    <div class="icon"><span class="icon"></span></div>
                    <%= text_field_tag :search_departure, params[:search_departure], class: "form-control" %>
                  </div>
                </div>
                <div class="col-md-6 mb-3 mb-lg-0 col-lg-3">
                  <label for="pt_arrival">Point d'arrivée: </label>
                  <div class="field-icon-wrap">
                    <div class="icon"><span class="icon"></span></div>
                    <%= text_field_tag :search_arrival, params[:search_arrival] , class: "form-control" %>
                  </div>
                </div>
                <div class="col-md-6 mb-3 mb-lg-0 col-lg-3">
                  <label for="pt_date"> Date de départ:</label>
                  <div class="field-icon-wrap">
                    <div class="icon"><span class="icon-calendar"></span></div>
                    <%= text_field_tag :search_date, params[:search_date] , class: "form-control" , id: "checkout_date"%>

                  </div>
                </div>
                <div class="col-md-6 col-lg-3 align-self-end">
                  <%= submit_tag 'Rechercher' , class: "btn btn-primary btn-block" %>
                </div>
              </div> 


            <% end %>
          </div>
        </div>
      </div>
      
    </div>

    <div class="site-section block-13 bg-light">
      <div class="container">
         <div class="row mb-5">
            <div class="col-md-7 section-heading">
              <span class="subheading-sm">Yuso-Covoit, une plateforme pour vous !</span>
              <p></p>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="nonloop-block-13 owl-carousel">


                  <div class="item">
                    <div class="block-34">
                      <div class="image">
                        <a href="#"><img src="assets/1.jpg" alt="Image placeholder"></a>
                      </div>
                      <div class="text">
                        <h2 class="heading">UN BIEN COMMUN</h2>
                        <ul class="specs">
                          <li><strong>
                            Le covoiturage est un bien commun : la valeur créée par les utilisateurs en covoiturant, comme conducteurs ou passagers, doit revenir aux utilisateurs. Grâce aux bénévoles l’animation de la plateforme est possible. Chacun peut apporter sa contribution en devenant bénévole afin d’améliorer la plateforme et de la faire connaître davantage, rejoignez-nous !</strong></li>
                        </ul>
                      </div>
                    </div>
                  </div>

                                    <div class="item">
                    <div class="block-34">
                      <div class="image">
                        <a href="#"><img src="assets/2.jpg" alt="Image placeholder"></a>
                      </div>
                      <div class="text">
                        <h2 class="heading">Libre</h2>
                        <ul class="specs">
                          <li><strong>
                            Nous nous ré-engageons à: 
                            Faire de la plateforme un bien commun, en restant libre dans nos choix et notre fonctionnement;
                            Protéger les données des utilisateurs pour que celles-ci soient seulement consacrées au bon déroulement du covoiturage;
                            Ne prendre aucune rémunération sur les trajets réalisés;
.</strong></li>
                        </ul>
                      </div>
                    </div>
                  </div>


                                    <div class="item">
                    <div class="block-34">
                      <div class="image">
                        <a href="#"><img src="assets/3.jpg" alt="Image placeholder"></a>
                      </div>
                      <div class="text">
                        <h2 class="heading">SANS COMISSION</h2>
                        <ul class="specs">
                          <li><strong>
                            Les prix sont fixés par les conducteurs, le site ne prélève aucune commission sur les trajets. Nous vivons grâce à vos dons. Le plus pour nos utilisateurs : des économies plus importantes pour les conducteurs et des voyages vraiment moins chers pour les passagers.</strong></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  
              </div>
    
            </div> <!-- .col-md-12 -->
          </div>
      </div>
    </div>

    <div class="site-section bg-light">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-7 section-heading">
            <span class="subheading-sm">Derniers trajets</span>
          </div>
        </div>
        <% @last_routes.each do |t| %>
        <div class="row">

          <div class="col-md-6 col-lg-4">            
           <div class="block-33">
              <div class="vcard d-flex mb-3">
                <% if User.find_by_id(t.user_id).photo.nil? %>
                  <div class="image align-self-center"><img src="assets/person_2.jpg" alt="Person here"></div>
                <% else %>
                <div class="image align-self-center"><img src="assets/avatar.png" alt="Person here"></div>
                <% end %>
                <div class="name-text align-self-center">
                  <h2 class="heading"><%= t.user.first_name %> <%= t.user.last_name %></h2>
                  <%= t.passenger_or_conducter %><br>
                  <%= t.place_number %> place(s) disponible(s)
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-6 col-lg-4">
            <div class="block-33">
              <div class="vcard d-flex mb-3">
                <div class="name-text align-self-center">
                  <h2 class="heading"><%= t.departure_point%> --> <%= t.arrival_point %></h2>
                  <%= t.departure_date %> <%= t.departure_time.strftime("%H:%M") %>
                </div>
              </div>
            </div>

          </div>
          <div class="col-md-6 col-lg-4">
            <div class="">
              <div class="vcard d-flex mb-3">
                <div class="name-text align-self-center">
                  <h2 class="heading"><div class="image align-self-center"><p><%= link_to t do %><span class="btn btn-primary">Voir annonce et réserver</span><% end %></p></div></h2>
                </div>
              </div>
            </div>
          </div> 
                
        </div>
        <br>
        <% end %>
        <div class="col-md-6 col-lg-4">

            <div class="">
              <div class="">
                <div class="name-text align-self-center">
                  <br><br><p><%= link_to all_routes_path do %><span class="btn btn-primary">Tous les trajets</span><% end %></p>
                </div>
              </div>
            </div>
          </div>  
      </div>
    </div>
    



    <div class="site-section bg-light">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-7 section-heading">
            <span class="subheading-sm">Avis</span>
            <h2 class="heading">Ce que disent les utilisateurs</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 col-lg-4">

            <div class="block-33">
              <div class="vcard d-flex mb-3">
                <div class="image align-self-center"><img src="assets/person_3.jpg" alt="Person here"></div>
                <div class="name-text align-self-center">
                  <h2 class="heading">Abderrahmen Masmoudi</h2>
                  <span class="meta">Passager</span>
                </div>
              </div>
              <div class="text">
                <blockquote>
                  <p>A travers Yuso-Covoit, j'ai trouvé les bons conducteurs à un prix convenable. Merci Yuso-Covoit!</p>
                </blockquote>
              </div>
            </div>

          </div>
          <div class="col-md-6 col-lg-4">

            <div class="block-33">
              <div class="vcard d-flex mb-3">
                <div class="image align-self-center"><img src="assets/person_2.jpg" alt="Person here"></div>
                <div class="name-text align-self-center">
                  <h2 class="heading">Chams Hamza</h2>
                  <span class="meta">Passager</span>
                </div>
              </div>
              <div class="text">
                <blockquote>
                  <p>Je suis très heureuse car j'ai trouvé un covoiturage à la dernière minute via Yuso-Covoit.</p>
                </blockquote>
              </div>
            </div>

          </div>
          <div class="col-md-6 col-lg-4">

            <div class="block-33">
              <div class="vcard d-flex mb-3">
                <div class="image align-self-center"><img src="assets/person_1.jpg" alt="Person here"></div>
                <div class="name-text align-self-center">
                  <h2 class="heading">Myriam Baklouti</h2>
                  <span class="meta">Conducteur</span>
                </div>
              </div>
              <div class="text">
                <blockquote>
                  <p>Cette application m'a permis de trouver des personnes avec lesquels j'ai partagé mon voyage.</p>
                </blockquote>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  


  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

  <script src="assets/js/jquery.min.js"></script>
  <script src="assets/js/jquery-migrate-3.0.1.min.js"></script>
  <script src="assets/js/popper.min.js"></script>
  <script src="assets/js/jquery.easing.1.3.js"></script>
  <script src="assets/js/jquery.waypoints.min.js"></script>
  <script src="assets/js/jquery.stellar.min.js"></script>
  <script src="assets/js/owl.carousel.min.js"></script>
  <script src="assets/js/jquery.magnific-popup.min.js"></script>
  <script src="assets/js/bootstrap.min.js"></script>
  <script src="assets/js/bootstrap-datepicker.js"></script>  
  <script src="assets/js/bootstrap-dialog.min.js"></script>
  <!-- <script src="assets/js/bootstrap_dialog4.js"></script> -->
  <script src="assets/js/aos.js"></script>
  <script src="assets/js/jquery.animateNumber.min.js"></script>
  <script src="assets/js/main.js"></script>
  
    
  </body>
</html>