config/routes.rb
Rails.application.routes.draw do


  resources :tests
  resources :messages
  resources :reservations
  post '/rate' => 'rater#create', :as => 'rate'
  get 'static_pages/home'

  get 'static_pages/contact'

  get 'static_pages/about_us'

  root 'static_pages#home'

  resources :routes do 
    resources :messages
  end
	resources :users do
	  resources :user_comments
	end
  resources :routes do
    resources :user_comments
  end


  devise_for :users , :path_prefix => 'devise' , 
  controllers: {  confirmations: 'confirmations'  ,registrations: 'registrations' }

  get 'trajets' => 'routes#index'
  get 'contact' => 'static_pages#contact'
  get 'all_routes' => 'routes#all_routes'
  post 'all_routes' => 'routes#all_routes'
  get 'manage' => 'users#manage_users'

end

app/models/user_comment.rb
class UserComment < ApplicationRecord
  belongs_to :user
  belongs_to :route
end

app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController
  before_action :set_user_comment, only: [:show, :edit, :update, :destroy]

  # GET /user_comments
  # GET /user_comments.json
  def index
    @user_comments = UserComment.all
  end

  # GET /user_comments/1
  # GET /user_comments/1.json
  def show
  end

  # GET /user_comments/new
  def new
    @user_comment = UserComment.new
  end

  # GET /user_comments/1/edit
  def edit
  end

  # POST /user_comments
  # POST /user_comments.json
  def create
    @user_comment = UserComment.new(user_comment_params)
    @route = Route.find_by_id(params[:route_id])
    @user_comment = @route.user_comments.create(user_comment_params)
    @user_comment.user_id = current_user.id
    @user_comment.route_id = @route.id


      if @user_comment.save
        flash[:success] = "Votre commentaire est ajouté avec succès !!"
        redirect_back(fallback_location: root_path)
      else
      end
    # end
  end

  # PATCH/PUT /user_comments/1
  # PATCH/PUT /user_comments/1.json
  def update
    respond_to do |format|
      if @user_comment.update(user_comment_params)
        format.html { redirect_to @user_comment, notice: 'User comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_comment }
      else
        format.html { render :edit }
        format.json { render json: @user_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_comments/1
  # DELETE /user_comments/1.json
  def destroy
    @user_comment.destroy
    respond_to do |format|
      format.html { redirect_to user_comments_url, notice: 'User comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_comment
      @user_comment = UserComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_comment_params
      params.require(:user_comment).permit(:content, :comment_validation, :user_id , :route_id)
    end
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

app/views/user_comments/_form.html.erb
<%= form_with(model: user_comment, local: true) do |form| %>
  <% if user_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_comment.errors.count, "error") %> prohibited this user_comment from being saved:</h2>

      <ul>
      <% user_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :user_comment_content %>
  </div>

  <div class="field">
    <%= form.label :comment_validation %>
    <%= form.text_field :comment_validation, id: :user_comment_comment_validation %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :user_comment_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_comments/edit.html.erb
<h1>Editing User Comment</h1>

<%= render 'form', user_comment: @user_comment %>

<%= link_to 'Show', @user_comment %> |
<%= link_to 'Back', user_comments_path %>

app/views/user_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Comment validation</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_comments.each do |user_comment| %>
      <tr>
        <td><%= user_comment.content %></td>
        <td><%= user_comment.comment_validation %></td>
        <td><%= user_comment.user %></td>
        <td><%= link_to 'Show', user_comment %></td>
        <td><%= link_to 'Edit', edit_user_comment_path(user_comment) %></td>
        <td><%= link_to 'Destroy', user_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Comment', new_user_comment_path %>

app/views/user_comments/new.html.erb
<h1>New User Comment</h1>

<%= render 'form', user_comment: @user_comment %>

<%= link_to 'Back', user_comments_path %>

app/views/user_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @user_comment.content %>
</p>

<p>
  <strong>Comment validation:</strong>
  <%= @user_comment.comment_validation %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_comment.user %>
</p>

<%= link_to 'Edit', edit_user_comment_path(@user_comment) %> |
<%= link_to 'Back', user_comments_path %>