config/routes.rb
Rails.application.routes.draw do


  resources :tests
  resources :messages
  resources :reservations
  post '/rate' => 'rater#create', :as => 'rate'
  get 'static_pages/home'

  get 'static_pages/contact'

  get 'static_pages/about_us'

  root 'static_pages#home'

  resources :routes do 
    resources :messages
  end
	resources :users do
	  resources :user_comments
	end
  resources :routes do
    resources :user_comments
  end


  devise_for :users , :path_prefix => 'devise' , 
  controllers: {  confirmations: 'confirmations'  ,registrations: 'registrations' }

  get 'trajets' => 'routes#index'
  get 'contact' => 'static_pages#contact'
  get 'all_routes' => 'routes#all_routes'
  post 'all_routes' => 'routes#all_routes'
  get 'manage' => 'users#manage_users'

end

app/models/route.rb
class Route < ApplicationRecord

  scope :departure, -> (departure_point) { where departure_point: departure_point }
  scope :arrival, -> (arrival_point) { where arrival_point: arrival_point }
  scope :date, -> (departure_date) { where departure_date: departure_date }

  belongs_to :user
  has_many :reservations
  has_many :user_comments
  has_many :messages

  validates :departure_point , presence: true
  validates :arrival_point , presence: true
  validates :departure_time , presence: true
  validates :place_number , presence: true
  # validates :price , presence: true
  validates :passenger_or_conducter, :acceptance => {:accept => ["Passager" , "Conducteur"]}

  def format_departure_date
      self.departure_time.strftime("%d %m,%Y") unless self.departure_time.nil?
  end

end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy ]
  

  # GET /routes
  # GET /routes.json
  def index
    if user_signed_in?
      @user= current_user
      @routes = @user.routes
      @reservations = @user.reservations
    end
  end

  def all_routes

    # Search routes by departure_point, arrival_oint and date
    if params[:search_departure].present? and params[:search_arrival].present? and params[:search_date].present?
  
      @routes = Route.departure(params[:search_departure]).arrival(params[:search_arrival]).date(params[:search_date])

    elsif params[:search_departure].present? and params[:search_arrival].present? 

       @routes = Route.departure(params[:search_departure]).arrival(params[:search_arrival])

    elsif params[:search_departure].present? and params[:search_date].present?
      
       @routes = Route.departure(params[:search_departure]).date(params[:search_date])  

    elsif params[:search_arrival].present?  and params[:search_date].present?

       @routes = Route.arrival(params[:search_arrival]).date(params[:search_date])

    elsif params[:search_departure].present? 

       @routes = Route.departure(params[:search_departure])

    elsif params[:search_date].present?

       @routes = Route.date(params[:search_date])

    elsif params[:search_arrival].present?  

       @routes = Route.arrival(params[:search_arrival]) 
    else 
      @routes = Route.all
    end

  end

  # GET /routes/1
  # GET /routes/1.json
  def show
    @user_comment = UserComment.new
    @comments = @route.user_comments
    @message = Message.new
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create

    if (user_signed_in?)
      @route = Route.new(route_params)
      @route.user_id = current_user.id

      respond_to do |format|
        if @route.save
          format.html { redirect_to trajets_path, notice: 'Votre trajet est bien enregistré!' }
          format.json { render :show, status: :created, location: @route }
        else
          format.html { render :new }
          format.json { render json: @route.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:departure_point, :arrival_point, :departure_date, :departure_time, :estimated_arrival_time, :place_number, :price, 
      :animal_permission, :smoker_permission, :luggage, :user_id , :passenger_or_conducter)
    end

    
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<% if user_signed_in? %>

<div class="item"  style="background-color: #0baccf; height: 150px;">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-10">
        <%= render 'layouts/custom_header' %>
      </div>
    </div>
  </div>
</div>
      
<div class="site-section block-13 bg-light">
  <div class="container" ng-app="">
     <div class="row mb-5">
        <div class="col-md-7 section-heading">
          <span class="subheading-sm">Déposer votre trajet</span>
        </div>
      </div>


        <div class="form-group">
          Je suis 
          <button class="btn btn-primary" ng-click="passenger = !passenger">Passager</button>
          <button class="btn btn-info" ng-click="conductor = !conductor">Conducteur</button>
        </div>

      <%= form_with(model: route, local: true , :html => { "ng-show" => "passenger" ,style: "display: block;"}) do |form| %>
        <% if route.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

            <ul>
            <% route.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <%= form.hidden_field :passenger_or_conducter, value: "Passager"%>

       
        <div class="form-group">
          <%= form.label :departure_point, "Point de départ" %>
          <%= form.collection_select :departure_point, City.all,  :city_name, :city_name,{ :include_blank => "Sélectionner votre point de départ" } , {class: "form-control" } %>
        </div>

        <div class="form-group">
          <%= form.label :arrival_point, "Point d'arrivée" %>
          <%= form.collection_select :arrival_point, City.all,  :city_name, :city_name,{ :include_blank => "Sélectionner votre point d'arrivée" } , {class: "form-control" } %>
        </div>

        <div class="form-group">
          <%= form.label :departure_date , "Date de départ" %>
          <%= form.date_select :departure_date, id: :route_departure_date ,class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :departure_time , "Heure de départ" %>
          <%= form.time_select :departure_time, id: :route_departure_time ,class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :place_number, "Nombre de places souhaitées" %>
          <%= form.number_field :place_number, id: :route_place_number ,class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :animal_permission, "Accepte les animaux" %>
          <%= form.check_box :animal_permission, id: :route_animal_permission ,class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :smoker_permission , "Je suis fumeur" %>
          <%= form.check_box :smoker_permission, id: :route_smoker_permission ,class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :luggage , "Je possède des bagages" %>
          <%= form.check_box :luggage, id: :route_luggage ,class: "form-control" %>
        </div>


        <center>
          <div class="actions">
            <%= form.submit "Déposer trajet" , class: "btn btn-primary" %>
          </div>
        </center>
    <% end %>

    <%= form_with(model: route, local: true , :html => {"ng-show" => "conductor"}) do |form| %>
        <% if route.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

            <ul>
            <% route.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <%= form.hidden_field :passenger_or_conducter, value: "Conducteur" %>

       
        <div class="form-group">
          <%= form.label :departure_point, "Point de départ" %>
          <%= form.collection_select :departure_point, City.all,  :city_name, :city_name,{ :include_blank => "Sélectionner votre point de départ" } , {class: "form-control" } %>
        </div>

        <div class="form-group">
          <%= form.label :arrival_point, "Point d'arrivée" %>
          <%= form.collection_select :arrival_point, City.all,  :city_name, :city_name,{ :include_blank => "Sélectionner votre point d'arrivée" } , {class: "form-control" } %>
        </div>

        <div class="form-group">
          <%= form.label :departure_date , "Date de départ" %>
          <%= form.date_select :departure_date, id: :route_departure_date ,class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :departure_time , "Heure de départ" %>
          <%= form.time_select :departure_time, id: :route_departure_time ,class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :estimated_arrival_time , "Date d'arrivée estimée" %>
          <%= form.datetime_select :estimated_arrival_time, id: :route_estimated_arrival_time ,class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :place_number, "Nombre de places disponbles" %>
          <%= form.number_field :place_number, id: :route_place_number ,class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :price , "Prix (en DT)" %>
          <%= form.text_field :price, id: :route_price ,class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :animal_permission, "Accepte les animaux" %>
          <%= form.check_box :animal_permission, id: :route_animal_permission ,class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :smoker_permission , "Je suis fumeur" %>
          <%= form.check_box :smoker_permission, id: :route_smoker_permission ,class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :luggage , "Je possède des bagages" %>
          <%= form.check_box :luggage, id: :route_luggage ,class: "form-control" %>
        </div>

        <center>
          <div class="actions">
            <%= form.submit "Déposer trajet" , class: "btn btn-primary"%>
          </div>
        </center>
    <% end %>



  </div>
</div>

<% else %>
  <%= render 'register' %>
<% end %>

app/views/routes/_register.html.erb
  <%= form_for(resource, as: resource_name, url: session_path(resource_name) , class: "form-horizontal form-material" , id: "loginform") do |f| %>


      <div class="form-group">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email" , class: 'form-control'%>
      </div>

      <div class="form-group">
          <%= f.label :password, "Mot de passe" %><br />
          <%= f.password_field :password, autocomplete: "off" , class: 'form-control' %>
      </div>

      <% if devise_mapping.rememberable? -%>
          <div class="field">
            <%= f.check_box :remember_me  %>
            <%= f.label :remember_me , "Se rappeler de moi" %>
          </div>
      <% end -%>
      <div class="form-group text-center">
        <div class="col-xs-12 p-b-20">
            <button class="btn btn-block btn-lg btn-info btn-rounded" type="submit">Se connecter</button>
        </div>

        <div class="form-group m-b-0">
            <div class="col-sm-12 text-center">
                Vous n'avez pas encore de compte? <a> <b> <%= link_to "S'inscrire" , new_user_registration_path ,class: "text-info m-l-5" %></b></a>
            </div>
        </div>
      </div>
  <% end %>

app/views/routes/all_routes.html.erb
<% if user_signed_in? %>
<div class="item"  style="background-color: #0baccf; height: 150px;">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-10">
        <%= render 'layouts/custom_header' %>
      </div>
    </div>
  </div>
</div>
<% end %>

<div class="site-section bg-light">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-7 section-heading">
            <span class="subheading-sm">Tous les trajets</span>
          </div>
        </div>
        <% if @routes.count == 0%>
        Aucun trajet déposé.
        <% if user_signed_in? %>
         <center> <p><%= link_to new_route_path do %><span class="btn btn-primary">Déposer un trajet</span><% end %></p></center>
        <% end %>
        <% else %>
        <table class="table">
            <% @routes.each do |r|%>
            <tr>
              <td colspan="2">
                <div class="row">
                  <div class="col-md-6 col-lg-4">
                   <div class="block-33">
                      <div class="vcard d-flex mb-3" style="width: 1000px;">
                        <% if r.user.photo_file_name.nil? %>
                          <div class="image align-self-center">
                            <img src="assets/person_2.jpg" alt="Photo">
                          </div>
                          <% else %>
                          <div class="image align-self-center">
                            <%= image_tag r.user.photo.url %>
                          </div>
                          <% end %>
                        <div class="name-text align-self-center">
                          <h2 class="heading"><%= r.departure_point%> --> <%= r.arrival_point%></h2>
                          <span class="meta">Date de départ: <%= r.departure_date %> <%= r.departure_time.strftime("%H:%M") %></span>
                          <span class="meta">Nombre de places disponibles: <%= r.place_number %></span>
                        </div>
                        <div class="image align-self-center"></div>
                        <% if user_signed_in? %>
                          <% if r.place_number == 0%>
                          <div class="image align-self-center"><p><span class="btn btn-primary">Complet</span></p></div>
                          <% else %>
                          <div class="image align-self-center"><p><%= link_to new_reservation_path(:route_res => r.id) do %><span class="btn btn-primary">Réserver</span><% end %></p></div>
                          <% end %>
                        <% end %>
                        <div class="image align-self-center"><p><%= link_to r do %><span class="btn btn-primary">Envoyer un message</span><% end %></p></div>
                      </div>
                    </div>
                  </div>       
                </div>
                </td>
            </tr>
            <% end %>
        </table>
        <% end %>
      </div>
    </div>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<% if user_signed_in? %>

<div class="item"  style="background-color: #0baccf; height: 150px;">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-10">
        <%= render 'layouts/custom_header' %>
      </div>
    </div>
  </div>
</div>
<center><h1>Mes trajets déposés</h1></center><br>
    <% if @routes.count == 0 %>
        <center>Aucun trajet déposé.
          <p><%= link_to new_route_path do %><span class="btn btn-primary">Déposer un trajet</span><% end %></p>
        </center>

    <% else %>
        <table class="table">
          <thead>
            <tr>
              <th>Point de départ</th>
              <th>Point d'arrivée</th>
              <th>Date de départ</th>
              <th>Nombre de place disponibles</th>
              <th>Prix (DT)</th>
              <th>Les personnes qui ont réservées</th>
              <th>Réservations</th>
              <th>Consuler</th>
            </tr>
          </thead>

          <tbody>
            <% @routes.each do |route| %>
              <tr>
                <td><%= route.departure_point %></td>
                <td><%= route.arrival_point %></td>
                <td><%= route.departure_time %></td>
                <td><%= route.place_number %></td>
                <td><%= route.price %></td>
                <% if route.reservations.count == 0 %>
                <td>Aucune réservation</td>
                <% else %>
                <td><% route.reservations.each do |r| %>
                  <%= r.user.first_name %> <%= r.user.last_name %> : <%= r.place_nbr %> place(s)
                  <% end %>
                </td>
                <% end %>
                <% if route.reservations.count == 0 %>
                <td>Pas de réservation</td>
                <% else %>
                <td><% route.reservations.each do |res| %>
                  <% @user = User.find_by_id(res.user_id)%>
                      <%= @user.first_name %> a réservé <%= res.place_nbr %> place(s).<br> 
                      Contact : <%= @user.phone_number %>                      
                    <% end %>
                </td>
                <% end %>
                <td><p><%= link_to route do %><span class="btn btn-primary">Voir</span><% end %></p></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <p><%= link_to new_route_path do %><span class="btn btn-primary">Déposer un trajet</span><% end %></p>
    <% end %>

    <br>
<br>
<center><h1>Mes réservations</h1></center><br>
    <% if @reservations.count == 0 %>
        <center>Aucune réservation.
        </center>

    <% else %>
        <table class="table">
          <thead>
            <tr>
              <th>Point de départ</th>
              <th>Point d'arrivée</th>
              <th>Date de départ</th>
              <th>Nombre de place réservées</th>
              <th>Prix (DT)</th>
            </tr>
          </thead>

          <tbody>
            <% @reservations.each do |res| %>
            <% @route = Route.find_by_id(res.route_id) %>
              <tr>
                <td><%= @route.departure_point %></td>
                <td><%= @route.arrival_point %></td>
                <td><%= @route.departure_date %> <%= @route.departure_time.strftime("%H:%M") %> </td>
                <td><%= res.place_nbr %></td>
                <td><%= @route.price * res.place_nbr%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    <% end %>
<% else %>
<div class="site-section bg-light">
      <div class="container">
        <%= render 'routes/register' %>
      </div>
</div>
<% end %>

app/views/routes/new.html.erb
<%= render 'form', route: @route %>

app/views/routes/show.html.erb
<% if user_signed_in? %>

<div class="item"  style="background-color: #0baccf; height: 150px;">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-10">
        <%= render 'layouts/custom_header' %>
      </div>
    </div>
  </div>
</div>

<div class="site-section block-13 bg-light">
  <div class="container" ng-app="">
     <div class="row mb-5">
        <div class="col-md-7 section-heading">
          <span class="subheading-sm">Trajet déposé par <%= @route.user.first_name %> </span>
        </div>
      </div>

      <table class="table">
        <tr>
          <td colspan="2">
          <p>
            <strong>Point de départ : </strong>
            <%= @route.departure_point %>
          </p>

          <p>
            <strong>Point d'arrivée : </strong>
            <%= @route.arrival_point %>
          </p>

          <p>
            <strong>Date de départ : </strong>
            <%= @route.departure_date %> <%= @route.departure_time.strftime("%H:%M") %>
          </p>

          <p>
            <strong>Nombre de places disponibles : </strong>
            <%= @route.place_number %>
          </p>

          <p>
            <strong>Prix:</strong>
            <%= @route.price %> dinars
          </p>

          <p>
            <strong>Possède un animal de companie : </strong>
            <% if  @route.animal_permission == false %>
            Non
            <% else %>
            Oui
            <% end %>
          </p>

          <p>
            <strong>Fumeur : </strong>
            <% if @route.smoker_permission == false %>
            Non
            <% else %>
            Oui
            <% end %>
          </p>

          <p>
            <strong>Contient du bagage : </strong>
            <% if @route.luggage == false %>
            Non
            <% else %>
            Oui
            <% end %>
          </p>
          </td>

          <td>
            <!-- <p><span class="btn btn-primary">Contacter l'annonceur</span></p> -->

          Numéro de Tél : <%= @route.user.phone_number %><br>

          <div class="col-md-12 pr-md-10">
          <%= form_for [@route, Message.new] do |form| %>
            <div class="form-group">
                <%= form.text_area :message_content, id: :message_content ,cols: "30" ,rows: "7" ,class: "form-control px-3 py-3" , placeholder: "Message" %>
            </div>
            <div class="form-group">
               <%= form.submit "Envoyer message" ,class: "btn btn-primary py-3 px-5" %>
            </div>
           <% end %>
        </div>
          </td>
        </tr>
      </table>


        <% if @route.place_number != 0%>
          <p><%= link_to new_reservation_path(:route_res => @route.id) do %><span class="btn btn-primary">Réserver une place</span><% end %></p>
        <% else %>
          <p><span class="btn btn-primary">Complet</span></p>
        <% end %>
      </div>
    </div>


<center>
  <div class="site-section">
    <div class="container">
      <div class="row block-9">
        <div class="col-md-6 pr-md-5">
          <%= form_for [@route, UserComment.new] do |form| %>
              <% if @user_comment.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@user_comment.errors.count, "error") %> prohibited this user_comment from being saved:</h2>

                  <ul>
                  <% @user_comment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
            <div class="form-group">
                <%= form.label :content, "Ajouter un commentaire" %>
                <%= form.text_area :content, id: :user_comment_content ,cols: "30" ,rows: "7" ,class: "form-control px-3 py-3" , placeholder: "Message" %>
            </div>
            <div class="form-group">
               <%= form.submit "Ajouter commentaire" ,class: "btn btn-primary py-3 px-5" %>
            </div>
           <% end %>
        </div>

        <% if @comments.count == 0 %>
        <% else %>
        <div class="block-21">
            <figure class="mr-3">
              <img src="assets/bg1.jpg" alt="" class="img-fluid">
            </figure>

            <div class="text">
              <h3 class="heading"><a href="#">Derniers commentaires</a></h3>
              <% @comments.each do |c| %>
              <div class="meta">
                <div><strong><%= c.content%></strong></div>
                <div><a href="#"> <%= c.created_at %> par <%= User.find_by_id(c.user_id).first_name %></a></div>
              </div>
              <% end %>
            </div>
        </div>
        <% end %>
        
      </div>
    </div>      
  </div>
</center>

<% else %>
<div class="site-section bg-light">
      <div class="container">
        <%= render 'routes/register' %>
      </div>
</div>
<% end %>