config/routes.rb
Rails.application.routes.draw do


  resources :tests
  resources :messages
  resources :reservations
  post '/rate' => 'rater#create', :as => 'rate'
  get 'static_pages/home'

  get 'static_pages/contact'

  get 'static_pages/about_us'

  root 'static_pages#home'

  resources :routes do 
    resources :messages
  end
	resources :users do
	  resources :user_comments
	end
  resources :routes do
    resources :user_comments
  end


  devise_for :users , :path_prefix => 'devise' , 
  controllers: {  confirmations: 'confirmations'  ,registrations: 'registrations' }

  get 'trajets' => 'routes#index'
  get 'contact' => 'static_pages#contact'
  get 'all_routes' => 'routes#all_routes'
  post 'all_routes' => 'routes#all_routes'
  get 'manage' => 'users#manage_users'

end

app/views/layouts/_custom_header.html.erb
<!-- Header -->  
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar" >
    <div class="container">
      <a class="navbar-brand">Yuso-Covoit</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>

      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          
          <li class="nav-item"><a><%= link_to "Mes trajets" ,trajets_path, class: "nav-link" %></a></li>
          <li class="nav-item"><a><%= link_to "Ma messagerie" ,messages_path, class: "nav-link" %></a></li>
          <% if user_signed_in? %> 
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name%></a>
                <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
                    <span class="with-arrow"><span class="bg-primary"></span></span>
                    <div class="d-flex no-block align-items-center p-15 text-white m-b-10">
                        
                        <div>
                            <h4><%= current_user.email %></h4>
                        </div>
                    </div>

                    <div class="dropdown-divider"></div>

                    <%= link_to  edit_user_registration_path , class: "dropdown-item" do %>
                    <i class="ti-settings m-r-5 m-l-5"></i>
                    Modifier profil<% end %>
                   
                    <%= link_to  destroy_user_session_path, method: :delete , class: "dropdown-item" do %>
                    <i class="fa fa-power-off m-r-5 m-l-5"></i>
                    Se déconnecter<% end %> 
                    
                    <div class="dropdown-divider"></div>
                    
                </div>
            </li> 
          <% end %>
        </ul>
      </div>
    </div>
</nav>
<!-- END Header -->

app/views/layouts/_footer.html.erb
  <footer class="footer">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-6 col-lg-4">
          <h3 class="heading-section">A propos de nous</h3>
          <p class="mb-5">Yuso-Covoit est une application web qui vous aide à trouver des covoiturages. Quelque soit vous êtes, vous pouvez partager une annonce de covoiturage ou chercehz une place d'une manière très simple.</p>
        </div>

        <div class="col-md-6 col-lg-4">
          <div class="block-23">
            <h3 class="heading-section">Contacter nous</h3>
              <ul>
                <li><span class="icon icon-map-marker"></span><span class="text">Route de Tenyour , Sfax</span></li>
                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+216 53 514 067</span></a></li>
                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">amasmoudi90@gmail.com</span></a></li>
                <li><span class="icon icon-clock-o"></span><span class="text">Lundi à Vendredi 8:00am - 5:00pm</span></li>
              </ul>
            </div>
        </div>
        
        
      </div>
      <div class="row pt-5">
        <div class="col-md-12 text-left">
          <p>
            Copyright 2018 Tous droits réservés .
          </p>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<!-- Header -->  
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand">Yuso-Covoit</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Yuso-Covoit
      </button>

      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a href="index.html" class="nav-link">Accueil</a></li>
          <% if not user_signed_in? %>
          <li class="nav-item"><a href="#" class="nav-link" data-toggle="modal" data-target="#sign_in_modal">Connexion</a></li>
          <% end %>
          
          
          <% if user_signed_in? %>
          <li class="nav-item"><a><%= link_to "Mes trajets" ,trajets_path, class: "nav-link" %></a></li>
          <li class="nav-item"><a><%= link_to "Ma messagerie" ,messages_path, class: "nav-link" %></a></li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name%></a>
              <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
                  <span class="with-arrow"><span class="bg-primary"></span></span>
                  <div class="d-flex no-block align-items-center p-15 text-white m-b-10">
                      
                      <div>
                          <h4><%= current_user.email %></h4>
                      </div>
                  </div>

                  <div class="dropdown-divider"></div>

                  <%= link_to  edit_user_registration_path , class: "dropdown-item" do %>
                  <i class="ti-settings m-r-5 m-l-5"></i>
                  Modifier profil<% end %>
                 
                  <%= link_to  destroy_user_session_path, method: :delete , class: "dropdown-item" do %>
                  <i class="fa fa-power-off m-r-5 m-l-5"></i>
                  Se déconnecter<% end %> 
                  
                  <div class="dropdown-divider"></div>
                  
              </div>
          </li> 
          <% else %>
          <li class="nav-item"><a><%= link_to "Inscription" ,new_user_registration_path, class: "nav-link" %></a></li>
          <% end %> 
          <li class="nav-item"><a><%= link_to "Contact" ,contact_path, class: "nav-link" %></a></li>
        </ul>
      </div>
    </div>
</nav>
<!-- END Header -->



<!-- Modal -->
<div class="modal fade" id="sign_in_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Yuso-Covoit</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>

          <div class="form-group">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email" , class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "new-password" , class: "form-control" %>
          </div>
          <center>
            <div class="actions">
              <%= f.submit "Se connecter" , class: "btn btn-primary" %>
            </div>
          </center>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_message.html.erb
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key)  %>">
            <%= value %>
      </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Covoiturage</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if controller_name == 'routes' %>
     <!-- Load JS files -->

      <%= javascript_include_tag 'jquery.min' %>
      <%= javascript_include_tag 'jquery-migrate-3.0.1.min' %>
      <%= javascript_include_tag 'popper.min' %>
      <%= javascript_include_tag 'jquery.easing.1.3' %>
      <%= javascript_include_tag 'jquery.waypoints.min' %>
      <%= javascript_include_tag 'jquery.stellar.min' %>
      <%= javascript_include_tag 'owl.carousel.min' %>
      <%= javascript_include_tag 'jquery.magnific-popup.min' %>
      <%= javascript_include_tag 'bootstrap.min' %>
      <%= javascript_include_tag 'bootstrap-datepicker' %>
      <%= javascript_include_tag 'aos' %>
      <%= javascript_include_tag 'jquery.animateNumber.min' %>
      <%= javascript_include_tag 'main' %>
      <%= javascript_include_tag 'angular.min' %>
    <% end %>
  </head>

  <body>
  	<% if controller_name != 'registrations' and controller_name != 'routes' and controller_name != 'sessions' and controller_name != 'reservations' and controller_name != 'messages'  %>
  		<%#= render 'layouts/header' %>
  	<% end %>
    <%= render 'layouts/message' %>
    <%= yield %>
    <% if controller_name != 'registrations'   %>
    	<%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>